// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.6.1
// source: bmc.proto

package bmc

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type PowerStatus int32

const (
	PowerStatus_UNKNOWN      PowerStatus = 0
	PowerStatus_ON           PowerStatus = 1
	PowerStatus_OFF          PowerStatus = 2
	PowerStatus_POWERING_ON  PowerStatus = 3
	PowerStatus_POWERING_OFF PowerStatus = 4
)

// Enum value maps for PowerStatus.
var (
	PowerStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "ON",
		2: "OFF",
		3: "POWERING_ON",
		4: "POWERING_OFF",
	}
	PowerStatus_value = map[string]int32{
		"UNKNOWN":      0,
		"ON":           1,
		"OFF":          2,
		"POWERING_ON":  3,
		"POWERING_OFF": 4,
	}
)

func (x PowerStatus) Enum() *PowerStatus {
	p := new(PowerStatus)
	*p = x
	return p
}

func (x PowerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PowerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_bmc_proto_enumTypes[0].Descriptor()
}

func (PowerStatus) Type() protoreflect.EnumType {
	return &file_bmc_proto_enumTypes[0]
}

func (x PowerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PowerStatus.Descriptor instead.
func (PowerStatus) EnumDescriptor() ([]byte, []int) {
	return file_bmc_proto_rawDescGZIP(), []int{0}
}

type BMCAccess struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConnectionString string `protobuf:"bytes,1,opt,name=connectionString,proto3" json:"connectionString,omitempty"`
}

func (x *BMCAccess) Reset() {
	*x = BMCAccess{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bmc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BMCAccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BMCAccess) ProtoMessage() {}

func (x *BMCAccess) ProtoReflect() protoreflect.Message {
	mi := &file_bmc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BMCAccess.ProtoReflect.Descriptor instead.
func (*BMCAccess) Descriptor() ([]byte, []int) {
	return file_bmc_proto_rawDescGZIP(), []int{0}
}

func (x *BMCAccess) GetConnectionString() string {
	if x != nil {
		return x.ConnectionString
	}
	return ""
}

type ServerPowerStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status PowerStatus `protobuf:"varint,1,opt,name=status,proto3,enum=bmc.PowerStatus" json:"status,omitempty"`
}

func (x *ServerPowerStatusResponse) Reset() {
	*x = ServerPowerStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bmc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerPowerStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerPowerStatusResponse) ProtoMessage() {}

func (x *ServerPowerStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bmc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerPowerStatusResponse.ProtoReflect.Descriptor instead.
func (*ServerPowerStatusResponse) Descriptor() ([]byte, []int) {
	return file_bmc_proto_rawDescGZIP(), []int{1}
}

func (x *ServerPowerStatusResponse) GetStatus() PowerStatus {
	if x != nil {
		return x.Status
	}
	return PowerStatus_UNKNOWN
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bmc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_bmc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_bmc_proto_rawDescGZIP(), []int{2}
}

var File_bmc_proto protoreflect.FileDescriptor

var file_bmc_proto_rawDesc = []byte{
	0x0a, 0x09, 0x62, 0x6d, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x62, 0x6d, 0x63,
	0x22, 0x37, 0x0a, 0x09, 0x42, 0x4d, 0x43, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x2a, 0x0a,
	0x10, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x72, 0x69, 0x6e,
	0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x22, 0x45, 0x0a, 0x19, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x62, 0x6d, 0x63, 0x2e, 0x50, 0x6f, 0x77,
	0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x2a, 0x4e, 0x0a, 0x0b, 0x50, 0x6f, 0x77,
	0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e,
	0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4e, 0x10, 0x01, 0x12, 0x07, 0x0a,
	0x03, 0x4f, 0x46, 0x46, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x50, 0x4f, 0x57, 0x45, 0x52, 0x49,
	0x4e, 0x47, 0x5f, 0x4f, 0x4e, 0x10, 0x03, 0x12, 0x10, 0x0a, 0x0c, 0x50, 0x4f, 0x57, 0x45, 0x52,
	0x49, 0x4e, 0x47, 0x5f, 0x4f, 0x46, 0x46, 0x10, 0x04, 0x32, 0xae, 0x01, 0x0a, 0x03, 0x42, 0x4d,
	0x43, 0x12, 0x48, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x50, 0x6f,
	0x77, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0e, 0x2e, 0x62, 0x6d, 0x63, 0x2e,
	0x42, 0x4d, 0x43, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x1a, 0x1e, 0x2e, 0x62, 0x6d, 0x63, 0x2e,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x2d, 0x0a, 0x0d, 0x50,
	0x6f, 0x77, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4f, 0x6e, 0x12, 0x0e, 0x2e, 0x62,
	0x6d, 0x63, 0x2e, 0x42, 0x4d, 0x43, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x1a, 0x0a, 0x2e, 0x62,
	0x6d, 0x63, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x2e, 0x0a, 0x0e, 0x50, 0x6f,
	0x77, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4f, 0x66, 0x66, 0x12, 0x0e, 0x2e, 0x62,
	0x6d, 0x63, 0x2e, 0x42, 0x4d, 0x43, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x1a, 0x0a, 0x2e, 0x62,
	0x6d, 0x63, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x6f, 0x70, 0x61, 0x33, 0x32,
	0x33, 0x2f, 0x6b, 0x69, 0x6d, 0x62, 0x61, 0x70, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x62, 0x6d, 0x63,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bmc_proto_rawDescOnce sync.Once
	file_bmc_proto_rawDescData = file_bmc_proto_rawDesc
)

func file_bmc_proto_rawDescGZIP() []byte {
	file_bmc_proto_rawDescOnce.Do(func() {
		file_bmc_proto_rawDescData = protoimpl.X.CompressGZIP(file_bmc_proto_rawDescData)
	})
	return file_bmc_proto_rawDescData
}

var file_bmc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_bmc_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_bmc_proto_goTypes = []interface{}{
	(PowerStatus)(0),                  // 0: bmc.PowerStatus
	(*BMCAccess)(nil),                 // 1: bmc.BMCAccess
	(*ServerPowerStatusResponse)(nil), // 2: bmc.ServerPowerStatusResponse
	(*Empty)(nil),                     // 3: bmc.Empty
}
var file_bmc_proto_depIdxs = []int32{
	0, // 0: bmc.ServerPowerStatusResponse.status:type_name -> bmc.PowerStatus
	1, // 1: bmc.BMC.GetServerPowerStatus:input_type -> bmc.BMCAccess
	1, // 2: bmc.BMC.PowerServerOn:input_type -> bmc.BMCAccess
	1, // 3: bmc.BMC.PowerServerOff:input_type -> bmc.BMCAccess
	2, // 4: bmc.BMC.GetServerPowerStatus:output_type -> bmc.ServerPowerStatusResponse
	3, // 5: bmc.BMC.PowerServerOn:output_type -> bmc.Empty
	3, // 6: bmc.BMC.PowerServerOff:output_type -> bmc.Empty
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_bmc_proto_init() }
func file_bmc_proto_init() {
	if File_bmc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bmc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BMCAccess); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bmc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerPowerStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bmc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bmc_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bmc_proto_goTypes,
		DependencyIndexes: file_bmc_proto_depIdxs,
		EnumInfos:         file_bmc_proto_enumTypes,
		MessageInfos:      file_bmc_proto_msgTypes,
	}.Build()
	File_bmc_proto = out.File
	file_bmc_proto_rawDesc = nil
	file_bmc_proto_goTypes = nil
	file_bmc_proto_depIdxs = nil
}
