// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package bmc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// BMCClient is the client API for BMC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BMCClient interface {
	PowerOn(ctx context.Context, in *BMCOperationRequest, opts ...grpc.CallOption) (*BMCOperationResponse, error)
}

type bMCClient struct {
	cc grpc.ClientConnInterface
}

func NewBMCClient(cc grpc.ClientConnInterface) BMCClient {
	return &bMCClient{cc}
}

func (c *bMCClient) PowerOn(ctx context.Context, in *BMCOperationRequest, opts ...grpc.CallOption) (*BMCOperationResponse, error) {
	out := new(BMCOperationResponse)
	err := c.cc.Invoke(ctx, "/bmc.BMC/PowerOn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BMCServer is the server API for BMC service.
// All implementations must embed UnimplementedBMCServer
// for forward compatibility
type BMCServer interface {
	PowerOn(context.Context, *BMCOperationRequest) (*BMCOperationResponse, error)
	mustEmbedUnimplementedBMCServer()
}

// UnimplementedBMCServer must be embedded to have forward compatible implementations.
type UnimplementedBMCServer struct {
}

func (UnimplementedBMCServer) PowerOn(context.Context, *BMCOperationRequest) (*BMCOperationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PowerOn not implemented")
}
func (UnimplementedBMCServer) mustEmbedUnimplementedBMCServer() {}

// UnsafeBMCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BMCServer will
// result in compilation errors.
type UnsafeBMCServer interface {
	mustEmbedUnimplementedBMCServer()
}

func RegisterBMCServer(s *grpc.Server, srv BMCServer) {
	s.RegisterService(&_BMC_serviceDesc, srv)
}

func _BMC_PowerOn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BMCOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BMCServer).PowerOn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bmc.BMC/PowerOn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BMCServer).PowerOn(ctx, req.(*BMCOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BMC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bmc.BMC",
	HandlerType: (*BMCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PowerOn",
			Handler:    _BMC_PowerOn_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bmc.proto",
}
