---
# Reusable section that keeps image and working directory consistent across jobs.
defaults: &defaults
  docker:
    - image: circleci/golang:1.9
  working_directory: /go/src/github.com/stopa323/kimbap

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Run Go linter
          command: make lint
      - run:
          name: Build Docker image
          command: make image

workflows:
  version: 2
  ci-workflow:
    jobs:
      - build
