---
# Reusable section that keeps base configuration consistent across jobs.
defaults: &defaults
  machine:
      image: ubuntu-2004:202010-01
  working_directory: ~/github.com/stopa323/kimbap
  environment:
    # Enable Docker BuildKit
    DOCKER_BUILDKIT: 1

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Run Go linter
          command: make lint
      - run:
          name: Build Docker image
          command: make image

workflows:
  version: 2
  ci-workflow:
    jobs:
      - build
